---
title: "UPA_single_dump_analysis_DK_2023-08-18"
author: "Alexander K. B. Andersen"
output: html_document
---

```{r,eval=TRUE,echo=FALSE}
print(paste("Time and date of screening:",Sys.time()))
```

## Introduction

```{r setup, include=F}

setwd("~/GitHub/upa_data_dump/")

# Import functions
source('~/GitHub/danbio.data.extraction.imaging/Denmark/functions/functions_old.R')

include_SAE=TRUE
iceland=FALSE


data_cut_1 <- as.Date("20220401",format="%Y%m%d")
data_cut_2 <- as.Date("20221007",format="%Y%m%d")

#import data using readxl package
library(readxl) #read_excel
library(writexl) #write_xlsx
library(parsedate)
library(formattable)
library(stringr)
library(tibble)
library(lubridate)
library("ggplot2")
library("plyr")

parse_new_dates = function(date_var){
  date_translate = list()
  date_translate["JAN"] = "01"
  date_translate["FEB"] = "02"
  date_translate["MAR"] = "03"
  date_translate["APR"] = "04"
  date_translate["MAY"] = "05"
  date_translate["JUN"] = "06"
  date_translate["JUL"] = "07"
  date_translate["AUG"] = "08"
  date_translate["SEP"] = "09"
  date_translate["OCT"] = "10"
  date_translate["NOV"] = "11"
  date_translate["DEC"] = "12"
  date_translate["   "] = "  "
  
  date_var[date_var ==""] = "         "
  
  date_mat = as.data.frame(t(matrix(unlist(strsplit(split = "",x=date_var)),nrow=9)))

  days = apply(date_mat[,1:2],1,FUN=function(x){paste(x,collapse="")})
  months = apply(data.frame(apply(date_mat[,3:5],1,FUN=function(x){paste(x,collapse="")})),1,FUN=function(x) {as.character(date_translate[x])})
  years = apply(date_mat[,6:9],1,FUN=function(x){paste(x,collapse="")})

  out = apply(cbind(years,months,days),1,FUN=function(x){paste(x,collapse="-")})
  out[out == "    -  -  "] = NA

  return(as.Date(out))
}

metadata=read_excel("~/GitHub/upa_data_dump/UPA_metadata_KFV.xlsx")

new_path = "~/GitHub/upa_data_dump/dump/UPA_20231010/"


pat="drk_patient_full.csv"
pre="drk_prescription_full.csv"

if(include_SAE==TRUE){
  sae="drk_seriousadverseevent_full.csv"
}
population="drk_population_full.csv"
visit="drk_visit_full.csv"
yearly="drk_yearly_full.csv"

pat_new = read.table(paste(new_path,pat,sep=""),sep=",",header=T)
pop_new = read.table(paste(new_path,population,sep=""),sep=",",header=T)
d_new_pre = read.table(paste(new_path,pre,sep=""),sep=",",header=T)
d_new_sae = read.table(paste(new_path, sae,sep=""),header = T,sep = ",")
d_new_visit = read.table(paste(new_path,visit,sep=""),header = T,sep = ",")
d_new_yearly = read.table(paste(new_path,yearly,sep=""),header = T,sep = ",")

#d_new_visit[d_new_visit$visitdate < 10000000 ,]$visitdate = NA

if(iceland){
  file="C:/Users/AAND0774/Documents/GitHub/upa_data_dump/dump/dump_island_20221207/eurospa_icebio_nov42022_version2_20221207.RData"
  load(file)
  print(paste("file used:",file,sep=""))
  pat_new=patients_dt
  d_new_pre=prescriptions_dt
  d_new_visit=visits_dt
  d_new_yearly=yearlys_dt
  d_new_pre$unique_prescription_id=paste("danbioordination",d_new_pre$drugstartdate,sep=".")
  colnames(d_new_pre)[colnames(d_new_pre)=="patientid"]="socialsecuritynumber"
  colnames(d_new_visit)[colnames(d_new_visit)=="patientid"]="socialsecuritynumber"
  colnames(d_new_yearly)[colnames(d_new_yearly)=="patientid"]="socialsecuritynumber"
  colnames(pat_new)[colnames(pat_new)=="patientid"]="socialsecuritynumber"
  include_SAE=FALSE
  
}

# get and convert dates
# convert drug start- and - stop dates into dates
d_new_pre$Prescription_start_date = as.Date(parse_date(d_new_pre$Prescription_start_date))
d_new_pre$Prescription_stop_date = as.Date(parse_date(d_new_pre$Prescription_stop_date))

# extracting inclusion date from the prescription ID.
tmp1 = gsub("[a-z]","",gsub("[\\.]","",gsub("[\\-]","",str_extract(pat_new$Unique_patient_id_danbio,"(patient|mappe)[\\-\\.][0-9]{4}-[0-9]{2}-[0-9]{2}"))))

## some of the dates still included 226 at the beginning of the date, which must be removed. 
tmp1<-gsub("^226","",tmp1)
pat_new$inclusiondate = as.Date(tmp1,format="%Y%m%d")

###############################################
# extracting registration date from the unique patient ID. 

tmp<-aggregate(d_new_pre$Prescription_start_date,by=list(d_new_pre$Unique_patient_id_danbio),min)
colnames(tmp)<-c("Unique_patient_id_danbio","registrationdate")

d_new_pre<-merge(d_new_pre,tmp,by="Unique_patient_id_danbio")


tmp<-aggregate(d_new_sae$Sae_start_date,by=list(d_new_sae$Unique_patient_id_danbio),min)
colnames(tmp)<-c("Unique_patient_id_danbio","registrationdate")

d_new_sae<-merge(d_new_sae,tmp,by="Unique_patient_id_danbio")

#################################################
# Adjust CPR (CPR is apparently imported as integer, which removes the first digit, if the first digit is 0)
pat_new$CPR<-as.character(pat_new$CPR)
pat_new$CPR=ifelse(nchar(pat_new$CPR)<10,paste0("0",pat_new$CPR),pat_new$CPR)
pop_new$CPR<-as.character(pop_new$CPR)
pop_new$CPR=ifelse(nchar(pop_new$CPR)<10,paste0("0",pop_new$CPR),pop_new$CPR)

##################################################
# convert dates into date
pat_new$Diagnosis_date = as.Date(parse_date(pat_new$Diagnosis_date))
pat_new$statusdiscontinuedateuserdecided = as.Date(parse_date(pat_new$statusdiscontinuedateuserdecided))

pop_new$Diagnosis_date = parse_new_dates(pop_new$Diagnosis_date)
pop_new$diag_year = parse_new_dates(pop_new$diag_year)
pop_new$CPR_status_dato = parse_new_dates(pop_new$CPR_status_dato)
pop_new$Max_visit = parse_new_dates(pop_new$Max_visit)
pop_new$Kontroldato_RA = parse_new_dates(pop_new$Kontroldato_RA)
pop_new$Kontroldato_SpA = parse_new_dates(pop_new$Kontroldato_SpA)
pop_new$Basmi_date = parse_new_dates(pop_new$Basmi_date)
pop_new$Xray_date_RA = parse_new_dates(pop_new$Xray_date_RA)
pop_new$Xray_columna_date = parse_new_dates(pop_new$Xray_columna_date)
pop_new$MR_columna_date = parse_new_dates(pop_new$MR_columna_date)
pop_new$Xray_sacro_joint_date = parse_new_dates(pop_new$Xray_sacro_joint_date)
pop_new$MR_sacro_joint_date = parse_new_dates(pop_new$MR_sacro_joint_date)
pop_new$DXA_scanning_date = parse_new_dates(pop_new$DXA_scanning_date)
pop_new$DAS_joints_RA_date = parse_new_dates(pop_new$DAS_joints_RA_date)
pop_new$CRP_date = parse_new_dates(pop_new$CRP_date)

d_new_sae$registrationdate = as.Date(parse_date(d_new_sae$registrationdate))
d_new_sae$Sae_start_date = as.Date(parse_date(d_new_sae$Sae_start_date))
d_new_sae$Sae_stop_date = as.Date(parse_date(d_new_sae$Sae_stop_date))

d_new_visit$Visit_date = as.Date(parse_date(d_new_visit$Visit_date))

d_new_yearly$Xray_date = as.Date(parse_date(d_new_yearly$Xray_date))
d_new_yearly$Xray_columna_date = as.Date(parse_date(d_new_yearly$Xray_columna_date))
d_new_yearly$MR_columna_date = as.Date(parse_date(d_new_yearly$MR_columna_date))
d_new_yearly$Xray_sacro_joint_date = as.Date(parse_date(d_new_yearly$Xray_sacro_joint_date))
d_new_yearly$DXA_scanning_date = as.Date(parse_date(d_new_yearly$DXA_scanning_date))
d_new_yearly$MR_sacro_joint_date = as.Date(parse_date(d_new_yearly$MR_sacro_joint_date))
###################################################
# GENERALSTATUSDATE IS NOT DELIVERED!! year_of_status is delivered on yearly-level instead
d_new_yearly$Year_of_status = as.Date(parse_date(d_new_yearly$Year_of_status))


# we remove all dates Jan 1st from yearly table ### NO WE DONT!!
#d_new_yearly$generalstatusdate[(as.integer(format(d_new_yearly$generalstatusdate,format="%Y%m%d")) %% 20000101) %% 10000 == 1] = NA
##################################################
# add CPR numbers. OBS: no need! They deliver it in the dump
## first for the new - THEY DELIVER CPR IN THE DUMP NOW!!!!
#patient_id_to_cpr_hash = as.list(pat_new$socialsecuritynumber)
#names(patient_id_to_cpr_hash) = pat_new$unique_patient_id

#d_new_pre <- add_cpr(d_new_pre, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)
#d_new_sae <- add_cpr(d_new_sae, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)
#d_new_visit <- add_cpr(d_new_visit, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)
#d_new_yearly <- add_cpr(d_new_yearly, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)


## version 2.0 august 18th 2023
cpr_to_id<-data.frame(pat_new$Unique_patient_id_danbio,pat_new$CPR)
colnames(cpr_to_id)<-c("Unique_patient_id_danbio","CPR")

d_new_pre<-merge(d_new_pre,cpr_to_id,by="Unique_patient_id_danbio")
d_new_sae<-merge(d_new_sae,cpr_to_id,by="Unique_patient_id_danbio")
d_new_visit<-merge(d_new_visit,cpr_to_id,by="Unique_patient_id_danbio")
d_new_yearly<-merge(d_new_yearly,cpr_to_id,by="Unique_patient_id_danbio")

```

```{r,eval=TRUE,echo=FALSE}
if(iceland==FALSE){
  print(paste("patient level file used:",new_path,pat,sep=""))
  print(paste("population level file used:",new_path,population,sep=""))
  print(paste("treatment level file used:",new_path,pre,sep=""))
  print(paste("SAE level file used:",new_path, sae,sep=""))
  print(paste("visit level file used:",new_path,visit,sep=""))
  print(paste("yearly level file used:",new_path,yearly,sep=""))
}
```

## 1 diagnosis

```{r,eval=TRUE,echo=F}

#(drugstartdate >= 20190101 | is.na(drugstopdate) |  drugstopdate >= 20190101)

# Unique cpr nr. with diagnosis in new dump
#print("the dump")
tmp = unique(pat_new[,c("CPR","Diagnosis")])
print(table(tmp$Diagnosis))

#unique_id_old = unique(pat_old$unique_patient_id)
unique_id_new = unique(pat_new$Unique_patient_id_danbio)

drugs = unique(c(d_new_pre$Prescription[startsWith(d_new_pre$Prescription,'BIOLOGIC') & d_new_pre$Prescription!="BIOLOGIC_MYCOPHENOLAT"],'DMARD_MTX','DMARD_MTX_SC','DMARD_MTX_IM','DMARD_SZS','DMARD_CHLOROCHINE','DMARD_LEFLUN'))

```

## 2. Period of registration for each variable

```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
if(iceland){
  options(warn=-1)
}
# Patient table
periode_start = c()
periode_stop = c()
vars = c()

pat_new$inclusiondate_int = as.numeric(format(pat_new$inclusiondate,format="%Y%m%d"))
for(var in setdiff(colnames(pat_new),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(pat_new$inclusiondate_int[!is.na(pat_new[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(pat_new$inclusiondate_int[!is.na(pat_new[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("Patient table")
print(out_tab[!(rownames(out_tab) %in% c("inclusiondate","inclusiondate_int")),])

# Population table
periode_start = c()
periode_stop = c()
vars = c()

pop_new$max_visit_int = as.numeric(format(pop_new$Max_visit,format="%Y%m%d"))
for(var in setdiff(colnames(pop_new),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(pop_new$max_visit_int[!is.na(pop_new[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(pop_new$max_visit_int[!is.na(pop_new[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("Population table")
print(out_tab[!(rownames(out_tab) %in% c("Max_visit","max_visit_int")),])

# Treatment table
periode_start = c()
periode_stop = c()
vars = c()
d_new_pre$registration_date_int = as.numeric(format(d_new_pre$registrationdate,format="%Y%m%d"))
for(var in setdiff(colnames(d_new_pre),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_pre$registration_date_int[!is.na(d_new_pre[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(d_new_pre$registration_date_int[!is.na(d_new_pre[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("Treatment table")

print(out_tab[!(rownames(out_tab) %in% c("registrationdate","registration_date_int")),])

if(include_SAE==TRUE){
  # SAE table
  periode_start = c()
  periode_stop = c()
  vars = c()
  d_new_sae$registration_date_int = as.numeric(format(d_new_sae$registrationdate,format="%Y%m%d"))
  for(var in setdiff(colnames(d_new_sae),c("X"))){
  
    periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_sae$registration_date_int[!is.na(d_new_sae[,var])],na.rm=T)),format = "%Y%m%d")))
    periode_stop = c(periode_stop, as.character(as.Date(as.character(max(d_new_sae$registration_date_int[!is.na(d_new_sae[,var])],na.rm=T)),format = "%Y%m%d")))
    vars = c(vars,var)
  }

  out_tab = data.frame(periode_start,periode_stop)
  rownames(out_tab) = unique(vars)
  
  print("SAE table")
  print(out_tab[!(rownames(out_tab) %in% c("registrationdate","registration_date_int")),])
}

# Visit table
periode_start = c()
periode_stop = c()
vars = c()
d_new_visit$visitdate_int = as.numeric(format(d_new_visit$Visit_date,format="%Y%m%d"))
for(var in setdiff(colnames(d_new_visit),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_visit$visitdate_int[!is.na(d_new_visit[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(d_new_visit$visitdate_int[!is.na(d_new_visit[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)


print("Visit Table")
print(out_tab[!(rownames(out_tab) %in% c("registrationdate","registration_date_int")),])

# yearly table
periode_start = c()
periode_stop = c()
vars = c()
d_new_yearly$generalstatusdate_int = as.integer(gsub("-","",as.character(d_new_yearly$Year_of_status)))
for(var in setdiff(colnames(d_new_yearly),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_yearly$generalstatusdate_int[!is.na(d_new_yearly[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop, as.character(as.Date(as.character(max(d_new_yearly$generalstatusdate_int[!is.na(d_new_yearly[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)


print("Yearly Table")
print(out_tab[!(rownames(out_tab) %in% c("generalstatusdate","generalstatusdate_int")),])


```

## 3. CPR-status overview
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
CPR_status=pop_new$CPR_status
CPR_status[CPR_status=="20"]<-"inaktiv, men tildelt personnummer"
CPR_status[CPR_status=="30"]<-"annulleret personnummer"
CPR_status[CPR_status=="50"]<-"slettet personnummer ved dobbeltnummer"
CPR_status[CPR_status=="60"]<-"ændret personnummer ved ændring af fødselsår"
CPR_status[CPR_status=="70"]<-"forsvundet"
CPR_status[CPR_status=="80"]<-"udrejst"
CPR_status[CPR_status=="90"]<-"død"

print(data.frame(table(CPR_status[CPR_status!="."])))
```


## 4. Period of registration per drug
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
# New visit table
periode_start = c()
periode_stop = c()
vars = c()

d_new_pre$registration_date_int = as.numeric(format(d_new_pre$registrationdate,format="%Y%m%d"))
for(drug in unique(d_new_pre$Prescription)){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_pre$registration_date_int[(d_new_pre$Prescription == drug)],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(d_new_pre$registration_date_int[(d_new_pre$Prescription == drug)],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,drug)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("New treatment table")
print(out_tab)


```

## 5. Estimated data cut date.

```{r,eval=TRUE,echo=F}

if(include_SAE==TRUE){
  df <- data.frame(a1 = c(as.character(max(pat_new$inclusiondate_int,na.rm = T)),
                          as.character(max(pop_new$max_visit_int,na.rm = T)),
                          as.character(max(d_new_pre$registration_date_int,na.rm = T)),
                          as.character(max(d_new_yearly$generalstatusdate_int,na.rm = T)),
                          as.character(max(d_new_visit$visitdate_int,na.rm = T)),
                          as.character(max(d_new_sae$registration_date_int,na.rm = T))))

  df = t(df)
  colnames(df)<-c("Patient table","Population table","Treatment table","Yearly table","Visit table","SAE table")
}else{
  df <- data.frame(a1 = c(as.character(max(pat_new$inclusiondate_int,na.rm = T)),
                          as.character(max(pop_new$max_visit_int,na.rm = T)),
                          as.character(max(d_new_pre$registration_date_int,na.rm = T)),
                          as.character(max(d_new_yearly$generalstatusdate_int,na.rm = T)),
                          as.character(max(d_new_visit$visitdate_int,na.rm = T))))

  df = t(df)
  colnames(df)<-c("Patient table","Population table","Treatment table","Yearly table","Visit table")
}


rownames(df)<-c("dump")
print(df)

```

## 6.ID counts.

```{r, eval=TRUE, echo=F}
## gather CPR nr. and ID's
CPR<-unique(pat_new$CPR)
pat_id<-unique(pat_new$Unique_patient_id_danbio)
hos_id<-unique(pat_new$hospital_id_danbio)
sae_id<-unique(d_new_sae$Unique_sae_id)
d_new_pre$unique_prescription_id=paste0(d_new_pre$CPR,"_",d_new_pre$Prescription,"_",d_new_pre$Prescription_start_date)
pre_id<-unique(d_new_pre$unique_prescription_id)

df<-data.frame(c(length(CPR),length(pat_id),length(hos_id),length(sae_id),length(pre_id)))
rownames(df)<- c("CPR nr.","Unique_patient_id_danbio","hospital_id_danbio","Unique_sae_id","unique_prescription_id")


#if(include_SAE==TRUE){
  ## gather SAE IDs
#  new_sae_ID=unique(d_new_sae$unique_sae_id)
#  df<-data.frame(c(length(new_pat_ID),    length(new_pre_ID),    length(new_sae_ID)))
#  rownames(df)<-c("CPR nr.","Prescription ID","SAE ID")
#}else{
#  df<-data.frame(c(length(new_pat_ID),    length(new_pre_ID)))
#  rownames(df)<-c("CPR nr.","Prescription ID")
#}

colnames(df)<-c("count")

formattable(df)

```

## 7. Treatment counts

```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
d_new_pre_old = d_new_pre

d_new_pre = unique(d_new_pre[,c("Unique_patient_id_danbio","Prescription","Prescription_start_date","Prescription_stop_date","registrationdate","CPR")])

# fixing drug vocabulary
d_new_pre[c("drugtype","drug_name","misc")] = str_split_fixed(d_new_pre$Prescription,"_",3)

d_new_pre[d_new_pre$drugtype == "PREDNISOLON",]$drug_name = "PREDNISOLON"
d_new_pre[d_new_pre$drugtype == "PREDNISOLON",]$drugtype = "STEROID"
d_new_pre[d_new_pre$drugtype == "NON",]$drugtype ="NON-BIOLOGIC"
d_new_pre[d_new_pre$drugtype == "NON-BIOLOGIC",]$drug_name =""
#d_new_pre[d_new_pre$drugtype == "FLURBIPROFEN",]$drug_name = "FLURBIPROFEN"
#d_new_pre[d_new_pre$drugtype == "FLURBIPROFEN",]$drugtype = "NSAID"

if(c("NODRUG") %in% d_new_pre$drugtype ){
  d_new_pre[d_new_pre$drugtype == "NODRUG",]$drug_name = "NODRUG"
}

# summarizing drug-name and -type from the two dumps into dataframes
df_new_name<-data.frame(cbind(table(d_new_pre$drug_name)))

colnames(df_new_name)<-"count"

df_new_type<-data.frame(cbind(table(d_new_pre$drugtype)))

#formattable(df_name)

#formattable(df_type)

#print("New")
#print(table(d_new_pre$drugname))
#print("Old")
#print(table(d_old_pre$drugname))

df_new_name$""<-""


# Divide table on types
## isolate biological drugs
biologic=unique(d_new_pre$drug_name[d_new_pre$drugtype=="BIOLOGIC"])

## isolate DMARDs
dmard=unique(d_new_pre$drug_name[d_new_pre$drugtype=="DMARD"])

## isolate NSAID's
nsaid=unique(d_new_pre$drug_name[d_new_pre$drugtype=="NSAID"])

## isolate other drugs
other=unique(d_new_pre$drug_name[d_new_pre$drugtype != "BIOLOGIC" & d_new_pre$drugtype != "NSAID" & d_new_pre$drugtype != "DMARD"])

print("for BDMARD's")
formattable(df_new_name[sort(biologic),1,drop=FALSE])

print("for DMARD's")
formattable(df_new_name[sort(dmard),1,drop=FALSE])

if(length(nsaid) > 0){
  print("for NSAID's")
  formattable(df_new_name[sort(nsaid),1,drop=FALSE])
}

print("for other types of drugs")
formattable(df_new_name[sort(other),1,drop=FALSE])


colnames(df_new_type)<-"count"
print("All types")
formattable(df_new_type)

```

### 8. Hospital ID overview.

```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
# for patients
hos_id=data.frame(table(pat_new$hospital_id))

colnames(hos_id)<-c("Hospital ID","patients")
rownames(hos_id) <- hos_id[,1]

hos_id = hos_id[,c(1,2)]

hos_id[is.na(hos_id)] = 0

hos_id_pat = hos_id[order(as.numeric(hos_id[,2]),decreasing = T),]

if("hospital_id" %in% colnames(d_new_pre_old) && length(d_new_pre_old$hospital_id[!is.na(d_new_pre_old$hospital_id)])>0){
  # for treatment
  hos_id=data.frame(table(d_new_pre_old$hospital_id))

  colnames(hos_id)<-c("Hospital ID","treatments")
  rownames(hos_id) <- hos_id[,1]

  hos_id[is.na(hos_id)] = 0

  hos_id_med = hos_id[,c(1,2)]

  # merge and show
  HOS_ID_final<-merge(hos_id_pat,hos_id_med)
}else{
  HOS_ID_final<-hos_id_pat
}
formattable(HOS_ID_final)

```

## 9. drugstartdates by drugtypes

```{r, eval=TRUE, echo=F, fig.width = 15}

drugtypes=unique(d_new_pre$drugtype)

for(x in drugtypes){
  if(!(x %in% c("NON-BIOLOGIC","NODRUG","MEDICINE","FLURBIPROFEN"))){
    temp<-d_new_pre[d_new_pre$drugtype==x,]
    temp<-temp[grepl("(start|_)date",colnames(temp))]
    
    values<-na.omit(temp[,1])
    #values<-values[values>as.Date("1800-01-01")]
  
    HIST<-hist(values,breaks="years",format="%Y-%m",main=paste(x," (amount:",nrow(temp),")"),xlab=" ",freq=TRUE,las=2)
  }
}


```

## 10. variable completeness (in percentage)

```{r, eval=TRUE, echo=F, fig.width = 15}
longest=max(length(colnames(pat_new)),
            length(colnames(pop_new)),
            length(colnames(d_new_pre)),
            length(colnames(d_new_sae)),
            length(colnames(d_new_visit)),
            length(colnames(d_new_yearly)))

completeness<-function(df,n){
  out=c()
  for(x in colnames(df)){
    percent=as.character(round((sum(!(is.na(df[x])))/nrow(df)) * 100,3))
    entry=paste0(x,": ",percent,"%")
    out=append(out,entry)
  }
  out=c(out,rep(NA,n-length(out)))
  return(out)
}

complete_df=data.frame("patient"=completeness(pat_new,longest),
                       "population"=completeness(pop_new,longest),
                       "Prescription"=completeness(d_new_pre,longest),
                       "SAE"=completeness(d_new_sae,longest),
                       "Visit"=completeness(d_new_visit,longest),
                       "Yearly"=completeness(d_new_yearly,longest))
formattable(complete_df)
```

### 11a. patient data based on diagnosis group
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
pat_new$diagnosis_group<-NA
# defining diagnosis groups
### RA-diagnoses ###
RA<-c("DIAGNOSIS_M05_9","DIAGNOSIS_M06_0","DIAGNOSIS_M06_9")
### PSA-diagnoses ###
PSA<-c("DIAGNOSIS_M07_3_A","DIAGNOSIS_M07_3_B")
### AS-diagnoses ###
AS<-c("DIAGNOSIS_M45_9","DIAGNOSIS_M45_9_H20_0","DIAGNOSIS_M45_9_M02_9",
      "DIAGNOSIS_M45_9_M07_2","DIAGNOSIS_M45_9_M07_4","DIAGNOSIS_M45_9_M07_5")
### sacroiliitis diagnoses ###
SAC<-c("DIAGNOSIS_M46_1")
### AxSPA-diagnoses ###
axspa<-c("DIAGNOSIS_M46_8_H20_0","DIAGNOSIS_M46_8_M02_9","DIAGNOSIS_M46_8_M07_2",
         "DIAGNOSIS_M46_8_M07_3","DIAGNOSIS_ M46_8_M07_4","DIAGNOSIS_M46_8_M07_4_7_5",
         "DIAGNOSIS_M46_8_M07_5")

other<-c("DIAGNOSIS_M13_0","DIAGNOSIS_M46_8_H20_0","DIAGNOSIS_M46_8_M02_9",
         "DIAGNOSIS_M46_8_M07_2","DIAGNOSIS_M46_8_M07_3","DIAGNOSIS_M46_8_M07_4",
         "DIAGNOSIS_M46_8_M07_4_7_5","DIAGNOSIS_M46_8_M07_5","DIAGNOSIS_M46_9")

pat_new$diagnosis_group[pat_new$Diagnosis %in% RA]<-"RA"
pat_new$diagnosis_group[pat_new$Diagnosis %in% PSA]<-"PSA"
pat_new$diagnosis_group[pat_new$Diagnosis %in% AS]<-"AS"
pat_new$diagnosis_group[pat_new$Diagnosis %in% axspa]<-"AxSPA"
pat_new$diagnosis_group[pat_new$Diagnosis %in% SAC]<-"SACROILIITIS"
pat_new$diagnosis_group[pat_new$Diagnosis %in% other]<-"OTHER"

## calculates patient age
date_pat=pat_new[,cols<-c("CPR","Unique_patient_id_danbio")]
### exrtact birth dates from CPR
date_pat$birth_day=str_extract(pat_new$CPR,"[0-9]{6}")
date_pat[c("birth_date","birth_year")] = c(str_extract(date_pat$birth_day,"[0-9]{4}"),
                                            str_extract(date_pat$birth_day,"[0-9]{2}$"))
### we assume that a patient is no more than 100 years old, so the 5-6 digits that are higher than the 3-4 digit of the data-cut-date is considered to be from the 1900's 
date_pat$birth_year=ifelse(date_pat$birth_year>as.integer(substr(format(data_cut_1,"%Y"),3,4)),
                           as.integer(paste0("19",date_pat$birth_year)),
                           as.integer(paste0("20",date_pat$birth_year)))
date_pat$birth_day=as.Date(paste0(date_pat$birth_date,date_pat$birth_year),format="%d%m%Y")
date_pat$age=as.integer(time_length(difftime(data_cut_1,date_pat$birth_day),"years"))
pat_new=merge(pat_new,date_pat[,c("Unique_patient_id_danbio","age")],by="Unique_patient_id_danbio")

### if the calculated age is less than the recorded age at diagnosis, it might be an error in CPR 
#### and will be adjusted for by taking the age at diagnosis and adding the years from diagnosis date to data_cut_date
pat_new$age=ifelse(!(is.na(pat_new$Age_at_diagnosis)) && pat_new$age<pat_new$Age_at_diagnosis,
                   pat_new$Age_at_diagnosis+as.integer(time_length(difftime(data_cut_1,pat_new$Diagnosis_date),"years")),
                   pat_new$age)


if(!("gender" %in% colnames(pat_new))){
  pat_new$gender=ifelse(as.integer(substr(pat_new$CPR,nchar(pat_new$CPR),nchar(pat_new$CPR))) %% 2 == 0, "FEMALE","MALE")
}

cats<-append(c("Gender"),unique(pat_new$gender))
cats<-append(cats,c("Age-groups","0-17","18-30","31-40","41-50","51-60","61-70","71-80","81+"))
cats<-append(cats,append(c("status discont. reasons"),unique(pat_new[,cols<-grep("statusdiscontinuereason",colnames(pat_new))])))
pat_df=data.frame(cats)

for(diag in unique(pat_new$diagnosis_group)){
  temp_df=pat_new[pat_new$diagnosis_group == diag,]
  pat_df[,diag]<-NA
  
  pat_df[pat_df$cats=="FEMALE",diag]=nrow(temp_df[temp_df$gender=="FEMALE",])
  pat_df[pat_df$cats=="MALE",diag]=nrow(temp_df[temp_df$gender=="MALE",])
  
  pat_df[pat_df$cats=="0-17",diag]=nrow(temp_df[temp_df$age<=17,])
  pat_df[pat_df$cats=="18-30",diag]=nrow(temp_df[temp_df$age>17 && temp_df$age<=30,])
  pat_df[pat_df$cats=="31-40",diag]=nrow(temp_df[temp_df$age>30 && temp_df$age<=40,])
  pat_df[pat_df$cats=="41-50",diag]=nrow(temp_df[temp_df$age>40 && temp_df$age<=50,])
  pat_df[pat_df$cats=="51-60",diag]=nrow(temp_df[temp_df$age>50 && temp_df$age<=60,])
  pat_df[pat_df$cats=="61-70",diag]=nrow(temp_df[temp_df$age>60 && temp_df$age<=70,])
  pat_df[pat_df$cats=="71-80",diag]=nrow(temp_df[temp_df$age>70 && temp_df$age<=80,])
  pat_df[pat_df$cats=="81+",diag]=nrow(temp_df[temp_df$age>80,])
  
  reasons<-unique(temp_df[,cols<-grep("statusdiscontinuereason",colnames(pat_new))])
  reasons_name<-names(temp_df)[grep("statusdiscontinuereason",colnames(pat_new))]
  for(x in reasons){
    pat_df[pat_df$cats==x,diag]=length(which(temp_df[[reasons_name]]==x))
  }
  
}
pat_df[pat_df$cats %in% c("Gender","Age-groups","status discont. reasons"),!(colnames(pat_df) %in% "cats")]="====="
formattable(pat_df)

```

## 11b. patient data based on treatment
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
pat_df=data.frame(cats)
drugtypes=unique(d_new_pre$drugtype)

for(type in drugtypes){
  temp_df<-d_new_pre[d_new_pre$drugtype==type,]
  pat_df[,type]<-NA
  
  PID=unique(temp_df$CPR)
  pat_temp=pat_new[pat_new$CPR %in% PID,]
  
  pat_df[pat_df$cats=="FEMALE",type]=nrow(pat_temp[pat_temp$gender=="FEMALE",])
  pat_df[pat_df$cats=="MALE",type]=nrow(pat_temp[pat_temp$gender=="MALE",])
  
  pat_df[pat_df$cats=="0-17",type]=nrow(pat_temp[pat_temp$age<=17,])
  pat_df[pat_df$cats=="18-30",type]=nrow(pat_temp[pat_temp$age>17 && pat_temp$age<=30,])
  pat_df[pat_df$cats=="31-40",type]=nrow(pat_temp[pat_temp$age>30 && pat_temp$age<=40,])
  pat_df[pat_df$cats=="41-50",type]=nrow(pat_temp[pat_temp$age>40 && pat_temp$age<=50,])
  pat_df[pat_df$cats=="51-60",type]=nrow(pat_temp[pat_temp$age>50 && pat_temp$age<=60,])
  pat_df[pat_df$cats=="61-70",type]=nrow(pat_temp[pat_temp$age>60 && pat_temp$age<=70,])
  pat_df[pat_df$cats=="71-80",type]=nrow(pat_temp[pat_temp$age>70 && pat_temp$age<=80,])
  pat_df[pat_df$cats=="81+",type]=nrow(pat_temp[pat_temp$age>80,])
  
  reasons=unique(pat_temp[,cols<-grep("statusdiscontinuereason",colnames(pat_temp))])
  reasons_name<-names(pat_temp)[grep("statusdiscontinuereason",colnames(pat_temp))]
  for(x in reasons){
    pat_df[pat_df$cats==x,type]=length(which(pat_temp[[reasons_name]]==x))
  }

}
pat_df[pat_df$cats %in% c("Gender","Age-groups","status discont. reasons"),!(colnames(pat_df) %in% "cats")]="====="
formattable(pat_df)
```

