---
title: "UPA_single_dump_analysis(ICELAND)"
author: "Alexander K. B. Andersen"
output: html_document
---
```{r,eval=TRUE,echo=FALSE}
print(paste("Time and date of screening:",Sys.time()))
```

## Introduction


```{r setup, include=F}

setwd("~/GitHub/upa_data_dump/")

# Import functions
source('~/GitHub/danbio.data.extraction.imaging/functions/functions.R')

include_SAE=TRUE
iceland=TRUE


data_cut_1 <- as.Date("20220401",format="%Y%m%d")
data_cut_2 <- as.Date("20221007",format="%Y%m%d")

#import data using readxl package
library(readxl) #read_excel
library(writexl) #write_xlsx
library(parsedate)
library(formattable)
library(stringr)
library(tibble)
library("ggplot2")
library("plyr")

metadata=read_excel("~/GitHub/upa_data_dump/UPA_metadata_KFV.xlsx")

new_path = "~/GitHub/upa_data_dump/dump/UPA_dump_20221103/"


pat="patients_dt_rkkp_UPA_6_20221009.txt"
pre="prescriptions_dt_rkkp_UPA_6_20221009.txt"

if(include_SAE==TRUE){
  sae="saes_dt_rkkp_UPA_6_20221009.txt"
}

visit="visits_dt_rkkp_UPA_6_20221009_20220930patched_20221031.txt"
yearly="yearlys_dt_rkkp_UPA_6_20221009_20220930patched_20221031.txt"

pat_new = read.table(paste(new_path,pat,sep=""),sep=";",header=T)
d_new_pre = read.table(paste(new_path,pre,sep=""),sep=";",header=T)
d_new_sae = read.table(paste(new_path, sae,sep=""),header = T,sep = ";")
d_new_visit = read.table(paste(new_path,visit,sep=""),header = T,sep = ";")
d_new_yearly = read.table(paste(new_path,yearly,sep=""),header = T,sep = ";")

d_new_visit[d_new_visit$visitdate < 10000000 ,]$visitdate = NA

if(iceland){
  file="C:/Users/AAND0774/Documents/GitHub/upa_data_dump/dump/dump_island_20221207/eurospa_icebio_nov42022_version2_20221207.RData"
  load(file)
  print(paste("file used:",file,sep=""))
  pat_new=patients_dt
  d_new_pre=prescriptions_dt
  d_new_visit=visits_dt
  d_new_yearly=yearlys_dt
  d_new_pre$unique_prescription_id=paste("danbioordination.",d_new_pre$drugstartdate,format="%Y%m%d",sep="")
  colnames(d_new_pre)[colnames(d_new_pre)=="patientid"]="socialsecuritynumber"
  colnames(d_new_visit)[colnames(d_new_visit)=="patientid"]="socialsecuritynumber"
  colnames(d_new_yearly)[colnames(d_new_yearly)=="patientid"]="socialsecuritynumber"
  colnames(pat_new)[colnames(pat_new)=="patientid"]="socialsecuritynumber"
  include_SAE=FALSE
}

# get and convert dates
# convert drug start- and - stop dates into dates
d_new_pre$drugstartdate = as.Date(parse_date(d_new_pre$drugstartdate))
d_new_pre$drugstopdate = as.Date(parse_date(d_new_pre$drugstopdate))

# extracting inclusion date from the prescription ID
tmp1 = gsub("[a-z]","",gsub("[\\.]","",gsub("[\\-]","",str_extract(pat_new$unique_patient_id,"(patient|mappe)[\\-\\.][0-9]{4}-[0-9]{2}-[0-9]{2}"))))

pat_new$inclusiondate = as.Date(tmp1,format="%Y%m%d")


# extracting registration date from the unique patient ID 
tmp1 = gsub("[a-z]","",gsub("[\\.]","",str_extract(d_new_pre$unique_prescription_id,"danbioordination.[0-9]{8}")))
tmp2 = gsub("[a-z]","",gsub("[\\.]","",str_extract(d_new_pre$unique_prescription_id,"danbiotreatment.[0-9]{8}")))
tmp3 = gsub("[a-z]","",gsub("[\\-]","",str_extract(d_new_pre$unique_prescription_id,"prescription.[0-9]{4}-[0-9]{2}-[0-9]{2}")))
tmp4 = gsub("[a-z]","",gsub("[\\-]","",str_extract(d_new_pre$unique_prescription_id,"danbioordination.[0-9]{4}-[0-9]{2}-[0-9]{2}")))

d_new_pre$registrationdate = as.Date(apply(data.frame(tmp1,tmp2,tmp3,tmp4),1,FUN=function(x){max(x,na.rm=T)}),format="%Y%m%d")

tmp1 = str_extract(d_new_pre$unique_prescription_id,"danbiohospitalnghospital_[0-9]+")
d_new_pre$hospital_id = tmp1

# convert dates into date
d_new_sae$registrationdate = as.Date(parse_date(d_new_sae$registrationdate))

d_new_sae$saestartdate = as.Date(parse_date(d_new_sae$saestartdate))
d_new_sae$saestopdate = as.Date(parse_date(d_new_sae$saestopdate))

d_new_visit$visitdate = as.Date(parse_date(d_new_visit$visitdate))

d_new_yearly$generalstatusdate = as.Date(parse_date(d_new_yearly$generalstatusdate))


# we remove all dates Jan 1st from yearly table
d_new_yearly$generalstatusdate[(as.integer(format(d_new_yearly$generalstatusdate,format="%Y%m%d")) %% 20000101) %% 10000 == 1] = NA

# add CPR numbers
## first for the new
patient_id_to_cpr_hash = as.list(pat_new$socialsecuritynumber)
names(patient_id_to_cpr_hash) = pat_new$unique_patient_id

d_new_pre <- add_cpr(d_new_pre, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)
d_new_sae <- add_cpr(d_new_sae, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)
d_new_visit <- add_cpr(d_new_visit, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)
d_new_yearly <- add_cpr(d_new_yearly, remove_unique_patient_id = FALSE, clean_weird_cpr = FALSE)

```

```{r,eval=TRUE,echo=FALSE}
if(iceland==FALSE){
  print(paste("patient level file used:",new_path,pat,sep=""))
  print(paste("treatment level file used:",new_path,pre,sep=""))
  print(paste("SAE level file used:",new_path, sae,sep=""))
  print(paste("visit level file used:",new_path,visit,sep=""))
  print(paste("yearly level file used:",new_path,yearly,sep=""))
}
```


## 1 diagnosis
```{r,eval=TRUE,echo=F}

#(drugstartdate >= 20190101 | is.na(drugstopdate) |  drugstopdate >= 20190101)

# Unique cpr nr. with diagnosis in new dump
#print("the dump")
tmp = unique(pat_new[,c("socialsecuritynumber","diagnosis")])
print(table(tmp$diagnosis))

#unique_id_old = unique(pat_old$unique_patient_id)
unique_id_new = unique(pat_new$unique_patient_id)

#drugs = unique(c(d_new_pre$drugname[startsWith(d_new_pre$drugname,'BIOLOGIC') & d_new_pre$drugname!="BIOLOGIC_MYCOPHENOLAT"],'DMARD_MTX','DMARD_MTX_SC','DMARD_MTX_IM','DMARD_SZS','DMARD_CHLOROCHINE','DMARD_LEFLUN'))

```

## 2. Period of registration for each variable
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
# Patient table
periode_start = c()
periode_stop = c()
vars = c()
pat_new$inclusiondate_int = as.numeric(format(pat_new$inclusiondate,format="%Y%m%d"))
for(var in setdiff(colnames(pat_new),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(pat_new$inclusiondate_int[!is.na(pat_new[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(pat_new$inclusiondate_int[!is.na(pat_new[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("Patient table")
print(out_tab[!(rownames(out_tab) %in% c("inclusiondate","inclusiondate_int")),])

# Treatment table
periode_start = c()
periode_stop = c()
vars = c()
d_new_pre$registration_date_int = as.numeric(format(d_new_pre$registrationdate,format="%Y%m%d"))
for(var in setdiff(colnames(d_new_pre),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_pre$registration_date_int[!is.na(d_new_pre[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(d_new_pre$registration_date_int[!is.na(d_new_pre[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("Treatment table")
print(out_tab[!(rownames(out_tab) %in% c("registrationdate","registration_date_int")),])

if(include_SAE==TRUE){
  # SAE table
  periode_start = c()
  periode_stop = c()
  vars = c()
  d_new_sae$registration_date_int = as.numeric(format(d_new_sae$registrationdate,format="%Y%m%d"))
  for(var in setdiff(colnames(d_new_sae),c("X"))){
  
    periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_sae$registration_date_int[!is.na(d_new_sae[,var])],na.rm=T)),format = "%Y%m%d")))
    periode_stop = c(periode_stop, as.character(as.Date(as.character(max(d_new_sae$registration_date_int[!is.na(d_new_sae[,var])],na.rm=T)),format = "%Y%m%d")))
    vars = c(vars,var)
  }

  out_tab = data.frame(periode_start,periode_stop)
  rownames(out_tab) = unique(vars)
  
  print("SAE table")
  print(out_tab[!(rownames(out_tab) %in% c("registrationdate","registration_date_int")),])
}

# Visit table
periode_start = c()
periode_stop = c()
vars = c()
d_new_visit$visitdate_int = as.numeric(format(d_new_visit$visitdate,format="%Y%m%d"))
for(var in setdiff(colnames(d_new_visit),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_visit$visitdate_int[!is.na(d_new_visit[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(d_new_visit$visitdate_int[!is.na(d_new_visit[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)


print("Visit Table")
print(out_tab[!(rownames(out_tab) %in% c("registrationdate","registration_date_int")),])

# yearly table
periode_start = c()
periode_stop = c()
vars = c()
d_new_yearly$generalstatusdate_int = as.numeric(format(d_new_yearly$generalstatusdate,format="%Y%m%d"))
for(var in setdiff(colnames(d_new_yearly),c("X"))){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_yearly$generalstatusdate_int[!is.na(d_new_yearly[,var])],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop, as.character(as.Date(as.character(max(d_new_yearly$generalstatusdate_int[!is.na(d_new_yearly[,var])],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,var)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)


print("Yearly Table")
print(out_tab[!(rownames(out_tab) %in% c("generalstatusdate","generalstatusdate_int")),])


```
## 3. Period of registration per drug
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
# New visit table
periode_start = c()
periode_stop = c()
vars = c()
d_new_pre$registration_date_int = as.numeric(format(d_new_pre$registrationdate,format="%Y%m%d"))
for(drug in unique(d_new_pre$drugname)){
  
  periode_start = c(periode_start, as.character(as.Date(as.character(min(d_new_pre$registration_date_int[(d_new_pre$drugname == drug)],na.rm=T)),format = "%Y%m%d")))
  periode_stop = c(periode_stop,   as.character(as.Date(as.character(max(d_new_pre$registration_date_int[(d_new_pre$drugname == drug)],na.rm=T)),format = "%Y%m%d")))
  vars = c(vars,drug)
}

out_tab = data.frame(periode_start,periode_stop)
rownames(out_tab) = unique(vars)

print("New treatment table")
print(out_tab)


```

## 4. Estimated data cut date
```{r,eval=TRUE,echo=F}

# Datoer bør castes i starten i stedet så vi ikke skal rette i denne kode hver gang vi bruger et nyt dump
if(include_SAE==TRUE){
  df <- data.frame(a1 = c(as.character(max(as.numeric(format(pat_new$inclusiondate,          format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_pre$registrationdate,     format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_yearly$generalstatusdate, format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_visit$visitdate,          format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_sae$registrationdate,     format="%Y%m%d")),na.rm = T))))

  df = t(df)
  colnames(df)<-c("Patient table","Treatment table","Yearly table","Visit table","SAE table")
}else{
  df <- data.frame(a1 = c(as.character(max(as.numeric(format(pat_new$inclusiondate,          format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_pre$registrationdate,     format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_yearly$generalstatusdate, format="%Y%m%d")),na.rm = T)),
                          as.character(max(as.numeric(format(d_new_visit$visitdate,          format="%Y%m%d")),na.rm = T))))

  df = t(df)
  colnames(df)<-c("Patient table","Treatment table","Yearly table","Visit table")
}

rownames(df)<-c("dump")
print(df)
#formattable(df)
```
## 5.ID counts
```{r, eval=TRUE, echo=F}
## gather CPR nr.
new_pat_ID=unique(d_new_pre$patient_id)

## gather prescription ID's
new_pre_ID=unique(d_new_pre$unique_prescription_id)

if(include_SAE==TRUE){
  ## gather SAE IDs
  new_sae_ID=unique(d_new_sae$unique_sae_id)
  df<-data.frame(c(length(new_pat_ID),    length(new_pre_ID),    length(new_sae_ID)))
  rownames(df)<-c("CPR nr.","Prescription ID","SAE ID")
}else{
  df<-data.frame(c(length(new_pat_ID),    length(new_pre_ID)))
  rownames(df)<-c("CPR nr.","Prescription ID")
}

colnames(df)<-c("count")

formattable(df)

```

## 6. Treatment counts
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
d_new_pre_old = d_new_pre

d_new_pre = unique(d_new_pre[,c("patient_id","drugname","drugstartdate","unique_prescription_id","registrationdate")])

# fixing drug vocabulary
d_new_pre[c("drugtype","drug_name","misc")] = str_split_fixed(d_new_pre$drugname,"_",3)

d_new_pre[d_new_pre$drugtype == "PREDNISOLON",]$drug_name = "PREDNISOLON"
d_new_pre[d_new_pre$drugtype == "PREDNISOLON",]$drugtype = "STEROID"

if(c("NODRUG") %in% d_new_pre$drugtype ){
  d_new_pre[d_new_pre$drugtype == "NODRUG",]$drug_name = "NODRUG"
}

# summarizing drug-name and -type from the two dumps into dataframes
df_new_name<-data.frame(cbind(table(d_new_pre$drug_name)))

colnames(df_new_name)<-"count"

df_new_type<-data.frame(cbind(table(d_new_pre$drugtype)))

#formattable(df_name)

#formattable(df_type)

#print("New")
#print(table(d_new_pre$drugname))
#print("Old")
#print(table(d_old_pre$drugname))

df_new_name$""<-""


# Divide table on types
## isolate biological drugs
biologic=unique(d_new_pre$drug_name[d_new_pre$drugtype=="BIOLOGIC"])

## isolate DMARDs
dmard=unique(d_new_pre$drug_name[d_new_pre$drugtype=="DMARD"])

## isolate NSAID's
nsaid=unique(d_new_pre$drug_name[d_new_pre$drugtype=="NSAID"])

## isolate other drugs
other=unique(d_new_pre$drug_name[d_new_pre$drugtype != "BIOLOGIC" & d_new_pre$drugtype != "NSAID" & d_new_pre$drugtype != "DMARD"])

print("for BDMARD's")
formattable(df_new_name[sort(biologic),1,drop=FALSE])

print("for DMARD's")
formattable(df_new_name[sort(dmard),1,drop=FALSE])

if(length(nsaid) > 0){
  print("for NSAID's")
  formattable(df_new_name[sort(nsaid),1,drop=FALSE])
}

print("for other types of drugs")
formattable(df_new_name[sort(other),1,drop=FALSE])


colnames(df_new_type)<-"count"
print("All types")
formattable(df_new_type)

```


### 7. Hospital ID overview
```{r, eval=TRUE, echo=F, fig.height = 15, fig.width = 10}
# for patients
hos_id=data.frame(table(pat_new$hospital_id))

colnames(hos_id)<-c("Hospital ID","patients")
rownames(hos_id) <- hos_id[,1]

hos_id = hos_id[,c(1,2)]

hos_id[is.na(hos_id)] = 0

hos_id_pat = hos_id[order(as.numeric(hos_id[,2]),decreasing = T),]

if("hospital_id" %in% colnames(d_new_pre_old) && length(d_new_pre_old$hospital_id[!is.na(d_new_pre_old$hospital_id)])>0){
  # for treatment
  hos_id=data.frame(table(d_new_pre_old$hospital_id))

  colnames(hos_id)<-c("Hospital ID","treatments")
  rownames(hos_id) <- hos_id[,1]

  hos_id[is.na(hos_id)] = 0

  hos_id_med = hos_id[,c(1,2)]

  # merge and show
  HOS_ID_final<-merge(hos_id_pat,hos_id_med)
}else{
  HOS_ID_final<-hos_id_pat
}
formattable(HOS_ID_final)

```